export const SEED_USERS = [
  {
    _id: "user_admin_01",
    name: "Admin User",
    email: "admin@eazybox.com",
    mobile: "9800000001",
    role: "ADMIN",
    department: "Executive Management",
    status: "ACTIVE",
    avatarUrl: "",
    lastActive: new Date(),
  },
  {
    _id: "user_aayusha_02",
    name: "Aayusha Paudel",
    email: "aayusha@eazybox.com",
    mobile: "9841234567",
    role: "SALES_EXECUTIVE",
    department: "Direct Sales",
    status: "ACTIVE",
    avatarUrl: "",
    lastActive: new Date(),
  },
  {
    _id: "user_simant_03",
    name: "Simant Shrestha",
    email: "simant@eazybox.com",
    mobile: "9812345678",
    role: "SALES_EXECUTIVE",
    department: "Direct Sales",
    status: "ACTIVE",
    avatarUrl: "",
    lastActive: new Date(),
  },
  {
    _id: "user_prabin_04",
    name: "Prabin Sharma",
    email: "prabin@eazybox.com",
    mobile: "9860123456",
    role: "SALES_MANAGER",
    department: "Sales Management",
    status: "ACTIVE",
    avatarUrl: "",
    lastActive: new Date(),
  },
  {
    _id: "user_ashok_05",
    name: "Ashok Timalsina",
    email: "ashok@eazybox.com",
    mobile: "9801122334",
    role: "SALES_EXECUTIVE",
    department: "Direct Sales",
    status: "ACTIVE",
    avatarUrl: "",
    lastActive: new Date(),
  },
  {
    _id: "user_alisha_06",
    name: "Alisha Karkki",
    email: "alisha@eazybox.com",
    mobile: "9849988776",
    role: "SALES_EXECUTIVE",
    department: "Inside Sales",
    status: "ACTIVE",
    avatarUrl: "",
    lastActive: new Date(),
  },
  {
    _id: "user_abhishek_07",
    name: "Abhishek Shrestha",
    email: "abhishek@eazybox.com",
    mobile: "9818877665",
    role: "SALES_EXECUTIVE",
    department: "Inside Sales",
    status: "ACTIVE",
    avatarUrl: "",
    lastActive: new Date(),
  },
];

export const SEED_CAMPAIGNS = [
  {
    _id: "camp_01",
    name: "Dashain Special Promo 2026",
    platform: "Meta Ads (FB/IG)",
    budget: 150000,
    spend: 112000,
    leadsCount: 145,
    confirmedCount: 68,
    salesCount: 54,
    revenue: 472500,
    conversionRate: 37.2,
    roas: 4.22,
    status: "ACTIVE",
  },
  {
    _id: "camp_02",
    name: "Retail Merchants Lead Gen - Q3",
    platform: "Meta Ads (FB/IG)",
    budget: 200000,
    spend: 185000,
    leadsCount: 190,
    confirmedCount: 75,
    salesCount: 61,
    revenue: 536500,
    conversionRate: 32.1,
    roas: 2.9,
    status: "ACTIVE",
  },
  {
    _id: "camp_03",
    name: "Supermarket Hardware Bundle",
    platform: "Google Search & Display",
    budget: 80000,
    spend: 78000,
    leadsCount: 65,
    confirmedCount: 22,
    salesCount: 18,
    revenue: 157500,
    conversionRate: 27.6,
    roas: 2.02,
    status: "PAUSED",
  },
  {
    _id: "camp_04",
    name: "Restaurant POS Hardware Kit",
    platform: "TikTok & Meta Ads",
    budget: 120000,
    spend: 95000,
    leadsCount: 110,
    confirmedCount: 42,
    salesCount: 35,
    revenue: 304500,
    conversionRate: 31.8,
    roas: 3.2,
    status: "ACTIVE",
  },
];

export const SEED_CUSTOMERS = [
  {
    _id: "cust_01",
    name: "Bishal Supermarket & Mart",
    mobile: "9841112233",
    email: "bishal.mart@gmail.com",
    address: "New Road, Kathmandu",
    salespersonId: "user_aayusha_02",
    salespersonName: "Aayusha Paudel",
    totalOrders: 4,
    totalUnits: 9,
    totalSpent: 78500,
    lastPurchaseDate: new Date("2026-09-24"),
  },
  {
    _id: "cust_02",
    name: "Himalayan Bakery & Cafe",
    mobile: "9802223344",
    email: "info@himalayanbakery.np",
    address: "Jhamsikhel, Lalitpur",
    salespersonId: "user_simant_03",
    salespersonName: "Simant Shrestha",
    totalOrders: 3,
    totalUnits: 6,
    totalSpent: 52000,
    lastPurchaseDate: new Date("2026-09-22"),
  },
  {
    _id: "cust_03",
    name: "Valley Pharmacy & Wellness",
    mobile: "9863334455",
    email: "valley.pharmacy@yahoo.com",
    address: "Lakeside, Pokhara",
    salespersonId: "user_prabin_04",
    salespersonName: "Prabin Sharma",
    totalOrders: 2,
    totalUnits: 5,
    totalSpent: 43500,
    lastPurchaseDate: new Date("2026-09-25"),
  },
  {
    _id: "cust_04",
    name: "Apex Electronics Hub",
    mobile: "9814445566",
    email: "apex.elec@gmail.com",
    address: "Main Road, Biratnagar",
    salespersonId: "user_ashok_05",
    salespersonName: "Ashok Timalsina",
    totalOrders: 2,
    totalUnits: 4,
    totalSpent: 35000,
    lastPurchaseDate: new Date("2026-09-20"),
  },
  {
    _id: "cust_05",
    name: "Everest Organic Store",
    mobile: "9845556677",
    email: "everest.organic@outlook.com",
    address: "Thamel, Kathmandu",
    salespersonId: "user_alisha_06",
    salespersonName: "Alisha Karkki",
    totalOrders: 3,
    totalUnits: 7,
    totalSpent: 60500,
    lastPurchaseDate: new Date("2026-09-23"),
  },
  {
    _id: "cust_06",
    name: "Golden Dragon Restaurant",
    mobile: "9806667788",
    email: "goldendragon.ktm@gmail.com",
    address: "Baneshwor, Kathmandu",
    salespersonId: "user_abhishek_07",
    salespersonName: "Abhishek Shrestha",
    totalOrders: 2,
    totalUnits: 3,
    totalSpent: 26000,
    lastPurchaseDate: new Date("2026-09-26"),
  },
];

export const SEED_SALES = [
  {
    _id: "sale_1001",
    saleId: "EZ-1001",
    customerName: "Bishal Supermarket & Mart",
    customerMobile: "9841112233",
    customerEmail: "bishal.mart@gmail.com",
    customerAddress: "New Road, Kathmandu",
    product: "EazyBox POS Hardware Suite",
    quantity: 3,
    sellingPrice: 9000,
    subtotal: 27000,
    unitCommission: 700,
    totalCommission: 2100,
    roundOff: 0,
    finalAmount: 27000,
    paymentMethod: "eSewa / Fonepay",
    source: "Meta Ads",
    campaign: "Dashain Special Promo 2026",
    salespersonId: "user_aayusha_02",
    salespersonName: "Aayusha Paudel",
    status: "DELIVERED",
    remark: "Customer requested urgent installation in Kathmandu store.",
    createdAt: new Date("2026-09-26T10:30:00Z"),
  },
  {
    _id: "sale_1002",
    saleId: "EZ-1002",
    customerName: "Himalayan Bakery & Cafe",
    customerMobile: "9802223344",
    customerEmail: "info@himalayanbakery.np",
    customerAddress: "Jhamsikhel, Lalitpur",
    product: "EazyBox Compact Terminal",
    quantity: 2,
    sellingPrice: 8500,
    subtotal: 17000,
    unitCommission: 500,
    totalCommission: 1000,
    roundOff: 0,
    finalAmount: 17000,
    paymentMethod: "Bank Transfer",
    source: "Meta Ads",
    campaign: "Retail Merchants Lead Gen - Q3",
    salespersonId: "user_simant_03",
    salespersonName: "Simant Shrestha",
    status: "COMPLETED",
    remark: "Paid in full via Everest Bank transfer.",
    createdAt: new Date("2026-09-25T14:15:00Z"),
  },
  {
    _id: "sale_1003",
    saleId: "EZ-1003",
    customerName: "Valley Pharmacy & Wellness",
    customerMobile: "9863334455",
    customerEmail: "valley.pharmacy@yahoo.com",
    customerAddress: "Lakeside, Pokhara",
    product: "EazyBox POS Pro",
    quantity: 4,
    sellingPrice: 9000,
    subtotal: 36000,
    unitCommission: 700,
    totalCommission: 2800,
    roundOff: 0,
    finalAmount: 36000,
    paymentMethod: "Fonepay QR",
    source: "Direct Referral",
    campaign: "Dashain Special Promo 2026",
    salespersonId: "user_prabin_04",
    salespersonName: "Prabin Sharma",
    status: "SHIPPED",
    remark: "Dispatched via Nepal Courier Service to Pokhara.",
    createdAt: new Date("2026-09-25T16:45:00Z"),
  },
  {
    _id: "sale_1004",
    saleId: "EZ-1004",
    customerName: "Apex Electronics Hub",
    customerMobile: "9814445566",
    customerEmail: "apex.elec@gmail.com",
    customerAddress: "Main Road, Biratnagar",
    product: "EazyBox Smart Terminal",
    quantity: 2,
    sellingPrice: 8500,
    subtotal: 17000,
    unitCommission: 500,
    totalCommission: 1000,
    roundOff: 0,
    finalAmount: 17000,
    paymentMethod: "Khalti",
    source: "Google Ads",
    campaign: "Supermarket Hardware Bundle",
    salespersonId: "user_ashok_05",
    salespersonName: "Ashok Timalsina",
    status: "CONFIRMED",
    remark: "Advance payment received. Preparing shipment.",
    createdAt: new Date("2026-09-24T11:20:00Z"),
  },
  {
    _id: "sale_1005",
    saleId: "EZ-1005",
    customerName: "Everest Organic Store",
    customerMobile: "9845556677",
    customerEmail: "everest.organic@outlook.com",
    customerAddress: "Thamel, Kathmandu",
    product: "EazyBox POS Suite",
    quantity: 3,
    sellingPrice: 9000,
    subtotal: 27000,
    unitCommission: 700,
    totalCommission: 2100,
    roundOff: 0,
    finalAmount: 27000,
    paymentMethod: "Cash on Delivery",
    source: "Meta Ads",
    campaign: "Restaurant POS Hardware Kit",
    salespersonId: "user_alisha_06",
    salespersonName: "Alisha Karkki",
    status: "PROCESSING",
    remark: "Scheduled for dispatch tomorrow morning.",
    createdAt: new Date("2026-09-24T09:10:00Z"),
  },
  {
    _id: "sale_1006",
    saleId: "EZ-1006",
    customerName: "Golden Dragon Restaurant",
    customerMobile: "9806667788",
    customerEmail: "goldendragon.ktm@gmail.com",
    customerAddress: "Baneshwor, Kathmandu",
    product: "EazyBox Compact POS",
    quantity: 1,
    sellingPrice: 9000,
    subtotal: 9000,
    unitCommission: 700,
    totalCommission: 700,
    roundOff: 0,
    finalAmount: 9000,
    paymentMethod: "eSewa",
    source: "Meta Ads",
    campaign: "Dashain Special Promo 2026",
    salespersonId: "user_abhishek_07",
    salespersonName: "Abhishek Shrestha",
    status: "DELIVERED",
    remark: "Setup and training completed on-site.",
    createdAt: new Date("2026-09-23T15:00:00Z"),
  },
  {
    _id: "sale_1007",
    saleId: "EZ-1007",
    customerName: "Subhash Garments Outlet",
    customerMobile: "9851122444",
    customerEmail: "subhash.fashion@gmail.com",
    customerAddress: "Chitwan, Narayangarh",
    product: "EazyBox POS Suite",
    quantity: 5,
    sellingPrice: 8500,
    subtotal: 42500,
    unitCommission: 500,
    totalCommission: 2500,
    roundOff: 0,
    finalAmount: 42500,
    paymentMethod: "Bank Transfer",
    source: "Meta Ads",
    campaign: "Retail Merchants Lead Gen - Q3",
    salespersonId: "user_aayusha_02",
    salespersonName: "Aayusha Paudel",
    status: "COMPLETED",
    remark: "Bulk purchase order for 5 cash counters.",
    createdAt: new Date("2026-09-22T13:30:00Z"),
  },
  {
    _id: "sale_1008",
    saleId: "EZ-1008",
    customerName: "City Mart Department Store",
    customerMobile: "9803332211",
    customerEmail: "citymart.ktm@gmail.com",
    customerAddress: "Tripureshwor, Kathmandu",
    product: "EazyBox POS Pro Suite",
    quantity: 6,
    sellingPrice: 9000,
    subtotal: 54000,
    unitCommission: 700,
    totalCommission: 4200,
    roundOff: 0,
    finalAmount: 54000,
    paymentMethod: "Bank Transfer",
    source: "Meta Ads",
    campaign: "Dashain Special Promo 2026",
    salespersonId: "user_simant_03",
    salespersonName: "Simant Shrestha",
    status: "COMPLETED",
    remark: "Full multi-counter deployment.",
    createdAt: new Date("2026-09-21T11:00:00Z"),
  },
];

export const SEED_LEADS = [
  {
    _id: "lead_01",
    name: "Greenland Departmental Store",
    mobile: "9841999888",
    email: "greenland.mart@gmail.com",
    source: "Meta Ads",
    campaign: "Dashain Special Promo 2026",
    salespersonId: "user_aayusha_02",
    salespersonName: "Aayusha Paudel",
    status: "INTERESTED",
    nextFollowUpDate: new Date("2026-09-28T10:00:00Z"),
    notes: [
      { author: "Aayusha Paudel", text: "Owner interested in 4 hardware units for new branch.", createdAt: new Date("2026-09-26T11:00:00Z") }
    ],
    followUps: [
      { date: new Date("2026-09-28T10:00:00Z"), note: "Call owner to confirm demo appointment.", status: "PENDING" }
    ],
    timeline: [
      { title: "Lead Captured", description: "Meta Ads Lead Form submitted.", user: "System", timestamp: new Date("2026-09-25T08:30:00Z") },
      { title: "Status Changed", description: "New -> Contacted -> Interested", user: "Aayusha Paudel", timestamp: new Date("2026-09-26T11:00:00Z") }
    ]
  },
  {
    _id: "lead_02",
    name: "Kathmandu Kitchen & Bar",
    mobile: "9801888777",
    email: "contact@ktmkitchen.np",
    source: "Meta Ads",
    campaign: "Restaurant POS Hardware Kit",
    salespersonId: "user_simant_03",
    salespersonName: "Simant Shrestha",
    status: "FOLLOW-UP",
    nextFollowUpDate: new Date("2026-09-27T15:00:00Z"),
    notes: [
      { author: "Simant Shrestha", text: "Requested quote for discounted pricing on 3 units.", createdAt: new Date("2026-09-25T16:00:00Z") }
    ],
    followUps: [
      { date: new Date("2026-09-27T15:00:00Z"), note: "Send revised quotation with Rs 8,500 rate.", status: "PENDING" }
    ],
    timeline: [
      { title: "Lead Captured", description: "Meta Ads Lead Form.", user: "System", timestamp: new Date("2026-09-24T12:00:00Z") }
    ]
  },
  {
    _id: "lead_03",
    name: "Pokhara Digital Store",
    mobile: "9862777666",
    email: "pokharadigital@gmail.com",
    source: "Google Ads",
    campaign: "Supermarket Hardware Bundle",
    salespersonId: "user_prabin_04",
    salespersonName: "Prabin Sharma",
    status: "CONFIRMED",
    nextFollowUpDate: new Date("2026-09-29T11:00:00Z"),
    notes: [
      { author: "Prabin Sharma", text: "Confirmed order for 2 units @ Rs 9000 each.", createdAt: new Date("2026-09-26T14:20:00Z") }
    ],
    followUps: [],
    timeline: [
      { title: "Confirmed", description: "Order confirmed by phone call.", user: "Prabin Sharma", timestamp: new Date("2026-09-26T14:20:00Z") }
    ]
  },
  {
    _id: "lead_04",
    name: "Urban Style Boutique",
    mobile: "9813666555",
    email: "urbanstyle@outlook.com",
    source: "Meta Ads",
    campaign: "Retail Merchants Lead Gen - Q3",
    salespersonId: "user_ashok_05",
    salespersonName: "Ashok Timalsina",
    status: "NEW",
    nextFollowUpDate: new Date("2026-09-27T16:00:00Z"),
    notes: [],
    followUps: [],
    timeline: [
      { title: "Lead Received", description: "Assigned to Ashok Timalsina", user: "System", timestamp: new Date("2026-09-27T09:15:00Z") }
    ]
  },
  {
    _id: "lead_05",
    name: "Sunrise General Store",
    mobile: "9849555444",
    email: "sunrisemart@gmail.com",
    source: "Organic Referral",
    campaign: "Dashain Special Promo 2026",
    salespersonId: "user_alisha_06",
    salespersonName: "Alisha Karkki",
    status: "CONVERTED",
    notes: [
      { author: "Alisha Karkki", text: "Sale converted into EZ-1005!", createdAt: new Date("2026-09-24T09:10:00Z") }
    ],
    followUps: [],
    timeline: [
      { title: "Converted to Sale", description: "Converted to Sale EZ-1005", user: "Alisha Karkki", timestamp: new Date("2026-09-24T09:10:00Z") }
    ]
  }
];

export const SEED_PAYMENTS = [
  {
    _id: "pay_01",
    salespersonId: "user_aayusha_02",
    salespersonName: "Aayusha Paudel",
    amount: 10000,
    paymentMethod: "eSewa Direct",
    date: new Date("2026-09-20"),
    reference: "ESW-998822",
    remark: "Advance commission payout for mid-month sales",
  },
  {
    _id: "pay_02",
    salespersonId: "user_simant_03",
    salespersonName: "Simant Shrestha",
    amount: 8000,
    paymentMethod: "Bank Transfer (NABIL)",
    date: new Date("2026-09-18"),
    reference: "NABIL-TXN-11029",
    remark: "Weekly commission release",
  },
  {
    _id: "pay_03",
    salespersonId: "user_prabin_04",
    salespersonName: "Prabin Sharma",
    amount: 5000,
    paymentMethod: "Fonepay QR",
    date: new Date("2026-09-22"),
    reference: "FONE-77221",
    remark: "Partial payout",
  },
];

export const SEED_AUDIT_LOGS = [
  {
    _id: "log_01",
    userId: "user_aayusha_02",
    userName: "Aayusha Paudel",
    userRole: "SALES_EXECUTIVE",
    action: "CREATE_SALE",
    module: "sales",
    recordId: "EZ-1001",
    details: "Aayusha created sale #EZ-1001 for Bishal Supermarket & Mart (Qty: 3, Revenue: Rs. 27,000)",
    createdAt: new Date("2026-09-26T10:30:00Z"),
  },
  {
    _id: "log_02",
    userId: "user_simant_03",
    userName: "Simant Shrestha",
    userRole: "SALES_EXECUTIVE",
    action: "UPDATE_STATUS",
    module: "sales",
    recordId: "EZ-1002",
    details: "Simant changed status of sale #EZ-1002 from Confirmed to Completed",
    createdAt: new Date("2026-09-25T14:15:00Z"),
  },
  {
    _id: "log_03",
    userId: "user_admin_01",
    userName: "Admin User",
    userRole: "ADMIN",
    action: "RECORD_COMMISSION_PAYMENT",
    module: "commission",
    recordId: "user_aayusha_02",
    details: "Admin recorded Rs. 10,000 commission payment to Aayusha Paudel",
    createdAt: new Date("2026-09-20T16:00:00Z"),
  },
  {
    _id: "log_04",
    userId: "user_prabin_04",
    userName: "Prabin Sharma",
    userRole: "SALES_MANAGER",
    action: "ASSIGN_LEAD",
    module: "leads",
    recordId: "lead_01",
    createdAt: new Date("2026-09-25T09:00:00Z"),
  },
];

export const SEED_PRODUCTS = [
  {
    _id: "prod_01",
    name: "EazyBox POS Hardware Suite",
    sku: "EZ-POS-HW-01",
    category: "Hardware",
    costPrice: 6500,
    sellingPrice: 9000,
    unitCommission: 500,
    stock: 50,
    description: "Complete POS Terminal with dual display, receipt printer & cash drawer.",
    status: "ACTIVE",
  },
  {
    _id: "prod_02",
    name: "EazyBox Compact Touch Terminal",
    sku: "EZ-TERM-MINI",
    category: "Hardware",
    costPrice: 11000,
    sellingPrice: 15000,
    unitCommission: 800,
    stock: 25,
    description: "Portable 10-inch Android Touchscreen POS Terminal.",
    status: "ACTIVE",
  },
  {
    _id: "prod_03",
    name: "Thermal Receipt Printer 80mm",
    sku: "EZ-PRN-80",
    category: "Accessories",
    costPrice: 3000,
    sellingPrice: 4500,
    unitCommission: 300,
    stock: 80,
    description: "High-speed 80mm thermal receipt printer with auto-cutter.",
    status: "ACTIVE",
  },
  {
    _id: "prod_04",
    name: "Omnidirectional 2D Barcode Scanner",
    sku: "EZ-SCN-2D",
    category: "Accessories",
    costPrice: 4000,
    sellingPrice: 6000,
    unitCommission: 400,
    stock: 45,
    description: "Desktop hands-free 1D/2D QR code barcode scanner.",
    status: "ACTIVE",
  },
  {
    _id: "prod_05",
    name: "EazyInvo Cloud ERP Annual License",
    sku: "EZ-SW-ANNUAL",
    category: "Software",
    costPrice: 4000,
    sellingPrice: 12000,
    unitCommission: 1000,
    stock: 999,
    description: "1-Year Cloud ERP, Inventory, Billing & CRM Software License.",
    status: "ACTIVE",
  },
];

